export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer style={{ backgroundColor: 'black', color: 'white', display: 'flex', justifyContent: 'center', padding: '10px', marginTop: '20px'}}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}
